# Generated by Django 5.0.3 on 2024-03-14 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='titel',
            new_name='title',
        ),
    ]
