# Generated by Django 5.0.3 on 2024-03-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
