# Generated by Django 5.0.3 on 2024-03-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='portfolio/images/certification')),
                ('url', models.URLField(blank=True)),
                ('skills', models.TextField()),
            ],
        ),
    ]
