# Generated by Django 5.0.3 on 2024-03-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
